// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 641736000;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__frb_api__cleanup_request_logs_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "cleanup_request_logs",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_older_than_days = <u32>::sse_decode(&mut deserializer);
            let api_max_delete = <Option<u32>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::frb_api::cleanup_request_logs(
                            api_older_than_days,
                            api_max_delete,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__frb_api__create_message_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_message",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_message = <crate::frb_api::CreateMessageRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::frb_api::create_message(api_message)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__frb_api__create_request_log_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_request_log",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_seed = <crate::frb_api::CreateRequestLogRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::frb_api::create_request_log(api_seed)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__frb_api__create_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_seed = <crate::frb_api::CreateSessionRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::frb_api::create_session(api_seed)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__frb_api__delete_messages_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "delete_messages",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            let api_message_ids = <Vec<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::frb_api::delete_messages(api_session_id, api_message_ids)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__frb_api__delete_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "delete_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::frb_api::delete_session(api_session_id)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__frb_api__get_request_log_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_request_log",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_log_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::frb_api::get_request_log(api_log_id)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__frb_api__list_messages_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_messages",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            let api_limit = <Option<u32>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::frb_api::list_messages(api_session_id, api_limit)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__frb_api__list_request_logs_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_request_logs",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <Option<String>>::sse_decode(&mut deserializer);
            let api_status =
                <Option<crate::frb_api::RequestLogStatus>>::sse_decode(&mut deserializer);
            let api_limit = <Option<u32>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::frb_api::list_request_logs(
                            api_session_id,
                            api_status,
                            api_limit,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__frb_api__list_sessions_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_sessions",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::frb_api::list_sessions()?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__frb_api__load_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "load_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::frb_api::load_session(api_session_id)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__frb_api__rename_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "rename_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            let api_session_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::frb_api::rename_session(api_session_id, api_session_name)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__frb_api__save_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "save_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_config = <crate::frb_api::SessionConfig>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::frb_api::save_session(api_config)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__frb_api__set_message_status_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "set_message_status",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_message_id = <String>::sse_decode(&mut deserializer);
            let api_status = <crate::frb_api::MessageStatus>::sse_decode(&mut deserializer);
            let api_error_message = <Option<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::frb_api::set_message_status(
                            api_message_id,
                            api_status,
                            api_error_message,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__frb_api__set_message_visibility_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "set_message_visibility",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_message_id = <String>::sse_decode(&mut deserializer);
            let api_visible = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::frb_api::set_message_visibility(api_message_id, api_visible)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__frb_api__set_workspace_dir_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "set_workspace_dir",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::frb_api::set_workspace_dir(api_path)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__frb_api__streaming_status_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "streaming_status_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::frb_api::StreamingStatus::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__frb_api__update_message_content_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "update_message_content",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_message_id = <String>::sse_decode(&mut deserializer);
            let api_content = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::frb_api::update_message_content(api_message_id, api_content)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::frb_api::CleanupRequestLogsResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_scanned = <u32>::sse_decode(deserializer);
        let mut var_deleted = <u32>::sse_decode(deserializer);
        let mut var_hasMoreExpired = <bool>::sse_decode(deserializer);
        return crate::frb_api::CleanupRequestLogsResult {
            scanned: var_scanned,
            deleted: var_deleted,
            has_more_expired: var_hasMoreExpired,
        };
    }
}

impl SseDecode for crate::frb_api::CreateMessageRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sessionId = <String>::sse_decode(deserializer);
        let mut var_role = <crate::frb_api::MessageRole>::sse_decode(deserializer);
        let mut var_content = <String>::sse_decode(deserializer);
        let mut var_visible = <bool>::sse_decode(deserializer);
        let mut var_status = <crate::frb_api::MessageStatus>::sse_decode(deserializer);
        return crate::frb_api::CreateMessageRequest {
            session_id: var_sessionId,
            role: var_role,
            content: var_content,
            visible: var_visible,
            status: var_status,
        };
    }
}

impl SseDecode for crate::frb_api::CreateRequestLogRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sessionId = <String>::sse_decode(deserializer);
        let mut var_provider = <String>::sse_decode(deserializer);
        let mut var_model = <String>::sse_decode(deserializer);
        let mut var_status = <crate::frb_api::RequestLogStatus>::sse_decode(deserializer);
        let mut var_requestTime = <String>::sse_decode(deserializer);
        let mut var_responseTime = <Option<String>>::sse_decode(deserializer);
        let mut var_durationMs = <Option<i64>>::sse_decode(deserializer);
        let mut var_promptTokens = <Option<i64>>::sse_decode(deserializer);
        let mut var_completionTokens = <Option<i64>>::sse_decode(deserializer);
        let mut var_totalTokens = <Option<i64>>::sse_decode(deserializer);
        let mut var_stopReason = <Option<String>>::sse_decode(deserializer);
        let mut var_redacted = <bool>::sse_decode(deserializer);
        let mut var_payloadTruncated = <bool>::sse_decode(deserializer);
        let mut var_requestPreviewJson = <Option<String>>::sse_decode(deserializer);
        let mut var_responsePreviewJson = <Option<String>>::sse_decode(deserializer);
        return crate::frb_api::CreateRequestLogRequest {
            session_id: var_sessionId,
            provider: var_provider,
            model: var_model,
            status: var_status,
            request_time: var_requestTime,
            response_time: var_responseTime,
            duration_ms: var_durationMs,
            prompt_tokens: var_promptTokens,
            completion_tokens: var_completionTokens,
            total_tokens: var_totalTokens,
            stop_reason: var_stopReason,
            redacted: var_redacted,
            payload_truncated: var_payloadTruncated,
            request_preview_json: var_requestPreviewJson,
            response_preview_json: var_responsePreviewJson,
        };
    }
}

impl SseDecode for crate::frb_api::CreateSessionRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sessionName = <String>::sse_decode(deserializer);
        let mut var_mode = <crate::frb_api::SessionMode>::sse_decode(deserializer);
        let mut var_mainApiConfigId = <String>::sse_decode(deserializer);
        let mut var_presetId = <String>::sse_decode(deserializer);
        let mut var_stWorldBookId = <Option<String>>::sse_decode(deserializer);
        return crate::frb_api::CreateSessionRequest {
            session_name: var_sessionName,
            mode: var_mode,
            main_api_config_id: var_mainApiConfigId,
            preset_id: var_presetId,
            st_world_book_id: var_stWorldBookId,
        };
    }
}

impl SseDecode for crate::frb_api::DeleteMessagesResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_deletedMessageIds = <Vec<String>>::sse_decode(deserializer);
        return crate::frb_api::DeleteMessagesResult {
            deleted_message_ids: var_deletedMessageIds,
        };
    }
}

impl SseDecode for crate::frb_api::DeleteResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_deleted = <bool>::sse_decode(deserializer);
        return crate::frb_api::DeleteResult {
            deleted: var_deleted,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::frb_api::MessageRecord> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::frb_api::MessageRecord>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::frb_api::RequestLogSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::frb_api::RequestLogSummary>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::frb_api::SessionSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::frb_api::SessionSummary>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::frb_api::LoadSessionResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_config = <crate::frb_api::SessionConfig>::sse_decode(deserializer);
        let mut var_runtime = <crate::frb_api::SessionRuntimeState>::sse_decode(deserializer);
        return crate::frb_api::LoadSessionResult {
            config: var_config,
            runtime: var_runtime,
        };
    }
}

impl SseDecode for crate::frb_api::MessageRecord {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_messageId = <String>::sse_decode(deserializer);
        let mut var_sessionId = <String>::sse_decode(deserializer);
        let mut var_role = <crate::frb_api::MessageRole>::sse_decode(deserializer);
        let mut var_floorNo = <Option<i64>>::sse_decode(deserializer);
        let mut var_content = <String>::sse_decode(deserializer);
        let mut var_visible = <bool>::sse_decode(deserializer);
        let mut var_status = <crate::frb_api::MessageStatus>::sse_decode(deserializer);
        let mut var_errorMessage = <Option<String>>::sse_decode(deserializer);
        let mut var_createdAt = <String>::sse_decode(deserializer);
        let mut var_updatedAt = <String>::sse_decode(deserializer);
        return crate::frb_api::MessageRecord {
            message_id: var_messageId,
            session_id: var_sessionId,
            role: var_role,
            floor_no: var_floorNo,
            content: var_content,
            visible: var_visible,
            status: var_status,
            error_message: var_errorMessage,
            created_at: var_createdAt,
            updated_at: var_updatedAt,
        };
    }
}

impl SseDecode for crate::frb_api::MessageRole {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::frb_api::MessageRole::System,
            1 => crate::frb_api::MessageRole::User,
            2 => crate::frb_api::MessageRole::Assistant,
            _ => unreachable!("Invalid variant for MessageRole: {}", inner),
        };
    }
}

impl SseDecode for crate::frb_api::MessageStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::frb_api::MessageStatus::Pending,
            1 => crate::frb_api::MessageStatus::Streaming,
            2 => crate::frb_api::MessageStatus::Completed,
            3 => crate::frb_api::MessageStatus::Error,
            _ => unreachable!("Invalid variant for MessageStatus: {}", inner),
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::frb_api::RequestLogStatus> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::frb_api::RequestLogStatus>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::frb_api::RequestLog {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_logId = <String>::sse_decode(deserializer);
        let mut var_sessionId = <String>::sse_decode(deserializer);
        let mut var_provider = <String>::sse_decode(deserializer);
        let mut var_model = <String>::sse_decode(deserializer);
        let mut var_status = <crate::frb_api::RequestLogStatus>::sse_decode(deserializer);
        let mut var_requestTime = <String>::sse_decode(deserializer);
        let mut var_responseTime = <Option<String>>::sse_decode(deserializer);
        let mut var_durationMs = <Option<i64>>::sse_decode(deserializer);
        let mut var_promptTokens = <Option<i64>>::sse_decode(deserializer);
        let mut var_completionTokens = <Option<i64>>::sse_decode(deserializer);
        let mut var_totalTokens = <Option<i64>>::sse_decode(deserializer);
        let mut var_stopReason = <Option<String>>::sse_decode(deserializer);
        let mut var_redacted = <bool>::sse_decode(deserializer);
        let mut var_payloadTruncated = <bool>::sse_decode(deserializer);
        let mut var_requestPreviewJson = <Option<String>>::sse_decode(deserializer);
        let mut var_responsePreviewJson = <Option<String>>::sse_decode(deserializer);
        return crate::frb_api::RequestLog {
            log_id: var_logId,
            session_id: var_sessionId,
            provider: var_provider,
            model: var_model,
            status: var_status,
            request_time: var_requestTime,
            response_time: var_responseTime,
            duration_ms: var_durationMs,
            prompt_tokens: var_promptTokens,
            completion_tokens: var_completionTokens,
            total_tokens: var_totalTokens,
            stop_reason: var_stopReason,
            redacted: var_redacted,
            payload_truncated: var_payloadTruncated,
            request_preview_json: var_requestPreviewJson,
            response_preview_json: var_responsePreviewJson,
        };
    }
}

impl SseDecode for crate::frb_api::RequestLogStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::frb_api::RequestLogStatus::Success,
            1 => crate::frb_api::RequestLogStatus::Error,
            _ => unreachable!("Invalid variant for RequestLogStatus: {}", inner),
        };
    }
}

impl SseDecode for crate::frb_api::RequestLogSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_logId = <String>::sse_decode(deserializer);
        let mut var_sessionId = <String>::sse_decode(deserializer);
        let mut var_provider = <String>::sse_decode(deserializer);
        let mut var_model = <String>::sse_decode(deserializer);
        let mut var_status = <crate::frb_api::RequestLogStatus>::sse_decode(deserializer);
        let mut var_requestTime = <String>::sse_decode(deserializer);
        let mut var_durationMs = <Option<i64>>::sse_decode(deserializer);
        let mut var_redacted = <bool>::sse_decode(deserializer);
        let mut var_payloadTruncated = <bool>::sse_decode(deserializer);
        return crate::frb_api::RequestLogSummary {
            log_id: var_logId,
            session_id: var_sessionId,
            provider: var_provider,
            model: var_model,
            status: var_status,
            request_time: var_requestTime,
            duration_ms: var_durationMs,
            redacted: var_redacted,
            payload_truncated: var_payloadTruncated,
        };
    }
}

impl SseDecode for crate::frb_api::SessionConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sessionId = <String>::sse_decode(deserializer);
        let mut var_sessionName = <String>::sse_decode(deserializer);
        let mut var_mode = <crate::frb_api::SessionMode>::sse_decode(deserializer);
        let mut var_mainApiConfigId = <String>::sse_decode(deserializer);
        let mut var_presetId = <String>::sse_decode(deserializer);
        let mut var_stWorldBookId = <Option<String>>::sse_decode(deserializer);
        let mut var_createdAt = <String>::sse_decode(deserializer);
        let mut var_updatedAt = <String>::sse_decode(deserializer);
        return crate::frb_api::SessionConfig {
            session_id: var_sessionId,
            session_name: var_sessionName,
            mode: var_mode,
            main_api_config_id: var_mainApiConfigId,
            preset_id: var_presetId,
            st_world_book_id: var_stWorldBookId,
            created_at: var_createdAt,
            updated_at: var_updatedAt,
        };
    }
}

impl SseDecode for crate::frb_api::SessionMode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::frb_api::SessionMode::St,
            1 => crate::frb_api::SessionMode::Rst,
            _ => unreachable!("Invalid variant for SessionMode: {}", inner),
        };
    }
}

impl SseDecode for crate::frb_api::SessionRuntimeState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sessionId = <String>::sse_decode(deserializer);
        let mut var_activeMessageId = <Option<String>>::sse_decode(deserializer);
        let mut var_streamingStatus = <crate::frb_api::StreamingStatus>::sse_decode(deserializer);
        let mut var_lastError = <Option<String>>::sse_decode(deserializer);
        let mut var_lastPromptTokenEstimate = <Option<i64>>::sse_decode(deserializer);
        let mut var_lastCompletionTokenEstimate = <Option<i64>>::sse_decode(deserializer);
        let mut var_lastUsedModel = <Option<String>>::sse_decode(deserializer);
        let mut var_lastRequestStartedAt = <Option<String>>::sse_decode(deserializer);
        let mut var_lastRequestFinishedAt = <Option<String>>::sse_decode(deserializer);
        let mut var_updatedAt = <String>::sse_decode(deserializer);
        return crate::frb_api::SessionRuntimeState {
            session_id: var_sessionId,
            active_message_id: var_activeMessageId,
            streaming_status: var_streamingStatus,
            last_error: var_lastError,
            last_prompt_token_estimate: var_lastPromptTokenEstimate,
            last_completion_token_estimate: var_lastCompletionTokenEstimate,
            last_used_model: var_lastUsedModel,
            last_request_started_at: var_lastRequestStartedAt,
            last_request_finished_at: var_lastRequestFinishedAt,
            updated_at: var_updatedAt,
        };
    }
}

impl SseDecode for crate::frb_api::SessionSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sessionId = <String>::sse_decode(deserializer);
        let mut var_sessionName = <String>::sse_decode(deserializer);
        let mut var_mode = <crate::frb_api::SessionMode>::sse_decode(deserializer);
        let mut var_updatedAt = <String>::sse_decode(deserializer);
        return crate::frb_api::SessionSummary {
            session_id: var_sessionId,
            session_name: var_sessionName,
            mode: var_mode,
            updated_at: var_updatedAt,
        };
    }
}

impl SseDecode for crate::frb_api::StreamingStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::frb_api::StreamingStatus::Idle,
            1 => crate::frb_api::StreamingStatus::Receiving,
            2 => crate::frb_api::StreamingStatus::Error,
            _ => unreachable!("Invalid variant for StreamingStatus: {}", inner),
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__frb_api__cleanup_request_logs_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__frb_api__create_message_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__frb_api__create_request_log_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__frb_api__create_session_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__frb_api__delete_messages_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__frb_api__delete_session_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__crate__frb_api__get_request_log_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__frb_api__list_messages_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__frb_api__list_request_logs_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__frb_api__list_sessions_impl(port, ptr, rust_vec_len, data_len),
        11 => wire__crate__frb_api__load_session_impl(port, ptr, rust_vec_len, data_len),
        12 => wire__crate__frb_api__rename_session_impl(port, ptr, rust_vec_len, data_len),
        13 => wire__crate__frb_api__save_session_impl(port, ptr, rust_vec_len, data_len),
        14 => wire__crate__frb_api__set_message_status_impl(port, ptr, rust_vec_len, data_len),
        15 => wire__crate__frb_api__set_message_visibility_impl(port, ptr, rust_vec_len, data_len),
        16 => wire__crate__frb_api__set_workspace_dir_impl(port, ptr, rust_vec_len, data_len),
        17 => {
            wire__crate__frb_api__streaming_status_default_impl(port, ptr, rust_vec_len, data_len)
        }
        18 => wire__crate__frb_api__update_message_content_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::frb_api::CleanupRequestLogsResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.scanned.into_into_dart().into_dart(),
            self.deleted.into_into_dart().into_dart(),
            self.has_more_expired.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::frb_api::CleanupRequestLogsResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::frb_api::CleanupRequestLogsResult>
    for crate::frb_api::CleanupRequestLogsResult
{
    fn into_into_dart(self) -> crate::frb_api::CleanupRequestLogsResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::frb_api::CreateMessageRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.session_id.into_into_dart().into_dart(),
            self.role.into_into_dart().into_dart(),
            self.content.into_into_dart().into_dart(),
            self.visible.into_into_dart().into_dart(),
            self.status.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::frb_api::CreateMessageRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::frb_api::CreateMessageRequest>
    for crate::frb_api::CreateMessageRequest
{
    fn into_into_dart(self) -> crate::frb_api::CreateMessageRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::frb_api::CreateRequestLogRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.session_id.into_into_dart().into_dart(),
            self.provider.into_into_dart().into_dart(),
            self.model.into_into_dart().into_dart(),
            self.status.into_into_dart().into_dart(),
            self.request_time.into_into_dart().into_dart(),
            self.response_time.into_into_dart().into_dart(),
            self.duration_ms.into_into_dart().into_dart(),
            self.prompt_tokens.into_into_dart().into_dart(),
            self.completion_tokens.into_into_dart().into_dart(),
            self.total_tokens.into_into_dart().into_dart(),
            self.stop_reason.into_into_dart().into_dart(),
            self.redacted.into_into_dart().into_dart(),
            self.payload_truncated.into_into_dart().into_dart(),
            self.request_preview_json.into_into_dart().into_dart(),
            self.response_preview_json.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::frb_api::CreateRequestLogRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::frb_api::CreateRequestLogRequest>
    for crate::frb_api::CreateRequestLogRequest
{
    fn into_into_dart(self) -> crate::frb_api::CreateRequestLogRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::frb_api::CreateSessionRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.session_name.into_into_dart().into_dart(),
            self.mode.into_into_dart().into_dart(),
            self.main_api_config_id.into_into_dart().into_dart(),
            self.preset_id.into_into_dart().into_dart(),
            self.st_world_book_id.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::frb_api::CreateSessionRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::frb_api::CreateSessionRequest>
    for crate::frb_api::CreateSessionRequest
{
    fn into_into_dart(self) -> crate::frb_api::CreateSessionRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::frb_api::DeleteMessagesResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.deleted_message_ids.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::frb_api::DeleteMessagesResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::frb_api::DeleteMessagesResult>
    for crate::frb_api::DeleteMessagesResult
{
    fn into_into_dart(self) -> crate::frb_api::DeleteMessagesResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::frb_api::DeleteResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.deleted.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::frb_api::DeleteResult {}
impl flutter_rust_bridge::IntoIntoDart<crate::frb_api::DeleteResult>
    for crate::frb_api::DeleteResult
{
    fn into_into_dart(self) -> crate::frb_api::DeleteResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::frb_api::LoadSessionResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.config.into_into_dart().into_dart(),
            self.runtime.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::frb_api::LoadSessionResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::frb_api::LoadSessionResult>
    for crate::frb_api::LoadSessionResult
{
    fn into_into_dart(self) -> crate::frb_api::LoadSessionResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::frb_api::MessageRecord {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.message_id.into_into_dart().into_dart(),
            self.session_id.into_into_dart().into_dart(),
            self.role.into_into_dart().into_dart(),
            self.floor_no.into_into_dart().into_dart(),
            self.content.into_into_dart().into_dart(),
            self.visible.into_into_dart().into_dart(),
            self.status.into_into_dart().into_dart(),
            self.error_message.into_into_dart().into_dart(),
            self.created_at.into_into_dart().into_dart(),
            self.updated_at.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::frb_api::MessageRecord {}
impl flutter_rust_bridge::IntoIntoDart<crate::frb_api::MessageRecord>
    for crate::frb_api::MessageRecord
{
    fn into_into_dart(self) -> crate::frb_api::MessageRecord {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::frb_api::MessageRole {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::System => 0.into_dart(),
            Self::User => 1.into_dart(),
            Self::Assistant => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::frb_api::MessageRole {}
impl flutter_rust_bridge::IntoIntoDart<crate::frb_api::MessageRole>
    for crate::frb_api::MessageRole
{
    fn into_into_dart(self) -> crate::frb_api::MessageRole {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::frb_api::MessageStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Pending => 0.into_dart(),
            Self::Streaming => 1.into_dart(),
            Self::Completed => 2.into_dart(),
            Self::Error => 3.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::frb_api::MessageStatus {}
impl flutter_rust_bridge::IntoIntoDart<crate::frb_api::MessageStatus>
    for crate::frb_api::MessageStatus
{
    fn into_into_dart(self) -> crate::frb_api::MessageStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::frb_api::RequestLog {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.log_id.into_into_dart().into_dart(),
            self.session_id.into_into_dart().into_dart(),
            self.provider.into_into_dart().into_dart(),
            self.model.into_into_dart().into_dart(),
            self.status.into_into_dart().into_dart(),
            self.request_time.into_into_dart().into_dart(),
            self.response_time.into_into_dart().into_dart(),
            self.duration_ms.into_into_dart().into_dart(),
            self.prompt_tokens.into_into_dart().into_dart(),
            self.completion_tokens.into_into_dart().into_dart(),
            self.total_tokens.into_into_dart().into_dart(),
            self.stop_reason.into_into_dart().into_dart(),
            self.redacted.into_into_dart().into_dart(),
            self.payload_truncated.into_into_dart().into_dart(),
            self.request_preview_json.into_into_dart().into_dart(),
            self.response_preview_json.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::frb_api::RequestLog {}
impl flutter_rust_bridge::IntoIntoDart<crate::frb_api::RequestLog> for crate::frb_api::RequestLog {
    fn into_into_dart(self) -> crate::frb_api::RequestLog {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::frb_api::RequestLogStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Success => 0.into_dart(),
            Self::Error => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::frb_api::RequestLogStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::frb_api::RequestLogStatus>
    for crate::frb_api::RequestLogStatus
{
    fn into_into_dart(self) -> crate::frb_api::RequestLogStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::frb_api::RequestLogSummary {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.log_id.into_into_dart().into_dart(),
            self.session_id.into_into_dart().into_dart(),
            self.provider.into_into_dart().into_dart(),
            self.model.into_into_dart().into_dart(),
            self.status.into_into_dart().into_dart(),
            self.request_time.into_into_dart().into_dart(),
            self.duration_ms.into_into_dart().into_dart(),
            self.redacted.into_into_dart().into_dart(),
            self.payload_truncated.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::frb_api::RequestLogSummary
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::frb_api::RequestLogSummary>
    for crate::frb_api::RequestLogSummary
{
    fn into_into_dart(self) -> crate::frb_api::RequestLogSummary {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::frb_api::SessionConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.session_id.into_into_dart().into_dart(),
            self.session_name.into_into_dart().into_dart(),
            self.mode.into_into_dart().into_dart(),
            self.main_api_config_id.into_into_dart().into_dart(),
            self.preset_id.into_into_dart().into_dart(),
            self.st_world_book_id.into_into_dart().into_dart(),
            self.created_at.into_into_dart().into_dart(),
            self.updated_at.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::frb_api::SessionConfig {}
impl flutter_rust_bridge::IntoIntoDart<crate::frb_api::SessionConfig>
    for crate::frb_api::SessionConfig
{
    fn into_into_dart(self) -> crate::frb_api::SessionConfig {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::frb_api::SessionMode {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::St => 0.into_dart(),
            Self::Rst => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::frb_api::SessionMode {}
impl flutter_rust_bridge::IntoIntoDart<crate::frb_api::SessionMode>
    for crate::frb_api::SessionMode
{
    fn into_into_dart(self) -> crate::frb_api::SessionMode {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::frb_api::SessionRuntimeState {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.session_id.into_into_dart().into_dart(),
            self.active_message_id.into_into_dart().into_dart(),
            self.streaming_status.into_into_dart().into_dart(),
            self.last_error.into_into_dart().into_dart(),
            self.last_prompt_token_estimate.into_into_dart().into_dart(),
            self.last_completion_token_estimate
                .into_into_dart()
                .into_dart(),
            self.last_used_model.into_into_dart().into_dart(),
            self.last_request_started_at.into_into_dart().into_dart(),
            self.last_request_finished_at.into_into_dart().into_dart(),
            self.updated_at.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::frb_api::SessionRuntimeState
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::frb_api::SessionRuntimeState>
    for crate::frb_api::SessionRuntimeState
{
    fn into_into_dart(self) -> crate::frb_api::SessionRuntimeState {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::frb_api::SessionSummary {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.session_id.into_into_dart().into_dart(),
            self.session_name.into_into_dart().into_dart(),
            self.mode.into_into_dart().into_dart(),
            self.updated_at.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::frb_api::SessionSummary
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::frb_api::SessionSummary>
    for crate::frb_api::SessionSummary
{
    fn into_into_dart(self) -> crate::frb_api::SessionSummary {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::frb_api::StreamingStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Idle => 0.into_dart(),
            Self::Receiving => 1.into_dart(),
            Self::Error => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::frb_api::StreamingStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::frb_api::StreamingStatus>
    for crate::frb_api::StreamingStatus
{
    fn into_into_dart(self) -> crate::frb_api::StreamingStatus {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::frb_api::CleanupRequestLogsResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.scanned, serializer);
        <u32>::sse_encode(self.deleted, serializer);
        <bool>::sse_encode(self.has_more_expired, serializer);
    }
}

impl SseEncode for crate::frb_api::CreateMessageRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.session_id, serializer);
        <crate::frb_api::MessageRole>::sse_encode(self.role, serializer);
        <String>::sse_encode(self.content, serializer);
        <bool>::sse_encode(self.visible, serializer);
        <crate::frb_api::MessageStatus>::sse_encode(self.status, serializer);
    }
}

impl SseEncode for crate::frb_api::CreateRequestLogRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.session_id, serializer);
        <String>::sse_encode(self.provider, serializer);
        <String>::sse_encode(self.model, serializer);
        <crate::frb_api::RequestLogStatus>::sse_encode(self.status, serializer);
        <String>::sse_encode(self.request_time, serializer);
        <Option<String>>::sse_encode(self.response_time, serializer);
        <Option<i64>>::sse_encode(self.duration_ms, serializer);
        <Option<i64>>::sse_encode(self.prompt_tokens, serializer);
        <Option<i64>>::sse_encode(self.completion_tokens, serializer);
        <Option<i64>>::sse_encode(self.total_tokens, serializer);
        <Option<String>>::sse_encode(self.stop_reason, serializer);
        <bool>::sse_encode(self.redacted, serializer);
        <bool>::sse_encode(self.payload_truncated, serializer);
        <Option<String>>::sse_encode(self.request_preview_json, serializer);
        <Option<String>>::sse_encode(self.response_preview_json, serializer);
    }
}

impl SseEncode for crate::frb_api::CreateSessionRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.session_name, serializer);
        <crate::frb_api::SessionMode>::sse_encode(self.mode, serializer);
        <String>::sse_encode(self.main_api_config_id, serializer);
        <String>::sse_encode(self.preset_id, serializer);
        <Option<String>>::sse_encode(self.st_world_book_id, serializer);
    }
}

impl SseEncode for crate::frb_api::DeleteMessagesResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.deleted_message_ids, serializer);
    }
}

impl SseEncode for crate::frb_api::DeleteResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.deleted, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::frb_api::MessageRecord> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::frb_api::MessageRecord>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::frb_api::RequestLogSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::frb_api::RequestLogSummary>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::frb_api::SessionSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::frb_api::SessionSummary>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::frb_api::LoadSessionResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::frb_api::SessionConfig>::sse_encode(self.config, serializer);
        <crate::frb_api::SessionRuntimeState>::sse_encode(self.runtime, serializer);
    }
}

impl SseEncode for crate::frb_api::MessageRecord {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.message_id, serializer);
        <String>::sse_encode(self.session_id, serializer);
        <crate::frb_api::MessageRole>::sse_encode(self.role, serializer);
        <Option<i64>>::sse_encode(self.floor_no, serializer);
        <String>::sse_encode(self.content, serializer);
        <bool>::sse_encode(self.visible, serializer);
        <crate::frb_api::MessageStatus>::sse_encode(self.status, serializer);
        <Option<String>>::sse_encode(self.error_message, serializer);
        <String>::sse_encode(self.created_at, serializer);
        <String>::sse_encode(self.updated_at, serializer);
    }
}

impl SseEncode for crate::frb_api::MessageRole {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::frb_api::MessageRole::System => 0,
                crate::frb_api::MessageRole::User => 1,
                crate::frb_api::MessageRole::Assistant => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::frb_api::MessageStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::frb_api::MessageStatus::Pending => 0,
                crate::frb_api::MessageStatus::Streaming => 1,
                crate::frb_api::MessageStatus::Completed => 2,
                crate::frb_api::MessageStatus::Error => 3,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::frb_api::RequestLogStatus> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::frb_api::RequestLogStatus>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::frb_api::RequestLog {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.log_id, serializer);
        <String>::sse_encode(self.session_id, serializer);
        <String>::sse_encode(self.provider, serializer);
        <String>::sse_encode(self.model, serializer);
        <crate::frb_api::RequestLogStatus>::sse_encode(self.status, serializer);
        <String>::sse_encode(self.request_time, serializer);
        <Option<String>>::sse_encode(self.response_time, serializer);
        <Option<i64>>::sse_encode(self.duration_ms, serializer);
        <Option<i64>>::sse_encode(self.prompt_tokens, serializer);
        <Option<i64>>::sse_encode(self.completion_tokens, serializer);
        <Option<i64>>::sse_encode(self.total_tokens, serializer);
        <Option<String>>::sse_encode(self.stop_reason, serializer);
        <bool>::sse_encode(self.redacted, serializer);
        <bool>::sse_encode(self.payload_truncated, serializer);
        <Option<String>>::sse_encode(self.request_preview_json, serializer);
        <Option<String>>::sse_encode(self.response_preview_json, serializer);
    }
}

impl SseEncode for crate::frb_api::RequestLogStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::frb_api::RequestLogStatus::Success => 0,
                crate::frb_api::RequestLogStatus::Error => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::frb_api::RequestLogSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.log_id, serializer);
        <String>::sse_encode(self.session_id, serializer);
        <String>::sse_encode(self.provider, serializer);
        <String>::sse_encode(self.model, serializer);
        <crate::frb_api::RequestLogStatus>::sse_encode(self.status, serializer);
        <String>::sse_encode(self.request_time, serializer);
        <Option<i64>>::sse_encode(self.duration_ms, serializer);
        <bool>::sse_encode(self.redacted, serializer);
        <bool>::sse_encode(self.payload_truncated, serializer);
    }
}

impl SseEncode for crate::frb_api::SessionConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.session_id, serializer);
        <String>::sse_encode(self.session_name, serializer);
        <crate::frb_api::SessionMode>::sse_encode(self.mode, serializer);
        <String>::sse_encode(self.main_api_config_id, serializer);
        <String>::sse_encode(self.preset_id, serializer);
        <Option<String>>::sse_encode(self.st_world_book_id, serializer);
        <String>::sse_encode(self.created_at, serializer);
        <String>::sse_encode(self.updated_at, serializer);
    }
}

impl SseEncode for crate::frb_api::SessionMode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::frb_api::SessionMode::St => 0,
                crate::frb_api::SessionMode::Rst => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::frb_api::SessionRuntimeState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.session_id, serializer);
        <Option<String>>::sse_encode(self.active_message_id, serializer);
        <crate::frb_api::StreamingStatus>::sse_encode(self.streaming_status, serializer);
        <Option<String>>::sse_encode(self.last_error, serializer);
        <Option<i64>>::sse_encode(self.last_prompt_token_estimate, serializer);
        <Option<i64>>::sse_encode(self.last_completion_token_estimate, serializer);
        <Option<String>>::sse_encode(self.last_used_model, serializer);
        <Option<String>>::sse_encode(self.last_request_started_at, serializer);
        <Option<String>>::sse_encode(self.last_request_finished_at, serializer);
        <String>::sse_encode(self.updated_at, serializer);
    }
}

impl SseEncode for crate::frb_api::SessionSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.session_id, serializer);
        <String>::sse_encode(self.session_name, serializer);
        <crate::frb_api::SessionMode>::sse_encode(self.mode, serializer);
        <String>::sse_encode(self.updated_at, serializer);
    }
}

impl SseEncode for crate::frb_api::StreamingStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::frb_api::StreamingStatus::Idle => 0,
                crate::frb_api::StreamingStatus::Receiving => 1,
                crate::frb_api::StreamingStatus::Error => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;
