// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_api.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustCoreApiImplPlatform extends BaseApiImpl<RustCoreWire> {
  RustCoreApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CreateMessageRequest dco_decode_box_autoadd_create_message_request(
    dynamic raw,
  );

  @protected
  CreateRequestLogRequest dco_decode_box_autoadd_create_request_log_request(
    dynamic raw,
  );

  @protected
  CreateSessionRequest dco_decode_box_autoadd_create_session_request(
    dynamic raw,
  );

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  RequestLogStatus dco_decode_box_autoadd_request_log_status(dynamic raw);

  @protected
  SessionConfig dco_decode_box_autoadd_session_config(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CreateMessageRequest dco_decode_create_message_request(dynamic raw);

  @protected
  CreateRequestLogRequest dco_decode_create_request_log_request(dynamic raw);

  @protected
  CreateSessionRequest dco_decode_create_session_request(dynamic raw);

  @protected
  DeleteMessagesResult dco_decode_delete_messages_result(dynamic raw);

  @protected
  DeleteResult dco_decode_delete_result(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<MessageRecord> dco_decode_list_message_record(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RequestLogSummary> dco_decode_list_request_log_summary(dynamic raw);

  @protected
  List<SessionSummary> dco_decode_list_session_summary(dynamic raw);

  @protected
  LoadSessionResult dco_decode_load_session_result(dynamic raw);

  @protected
  MessageRecord dco_decode_message_record(dynamic raw);

  @protected
  MessageRole dco_decode_message_role(dynamic raw);

  @protected
  MessageStatus dco_decode_message_status(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  RequestLogStatus? dco_decode_opt_box_autoadd_request_log_status(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  RequestLog dco_decode_request_log(dynamic raw);

  @protected
  RequestLogStatus dco_decode_request_log_status(dynamic raw);

  @protected
  RequestLogSummary dco_decode_request_log_summary(dynamic raw);

  @protected
  SessionConfig dco_decode_session_config(dynamic raw);

  @protected
  SessionMode dco_decode_session_mode(dynamic raw);

  @protected
  SessionRuntimeState dco_decode_session_runtime_state(dynamic raw);

  @protected
  SessionSummary dco_decode_session_summary(dynamic raw);

  @protected
  StreamingStatus dco_decode_streaming_status(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CreateMessageRequest sse_decode_box_autoadd_create_message_request(
    SseDeserializer deserializer,
  );

  @protected
  CreateRequestLogRequest sse_decode_box_autoadd_create_request_log_request(
    SseDeserializer deserializer,
  );

  @protected
  CreateSessionRequest sse_decode_box_autoadd_create_session_request(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  RequestLogStatus sse_decode_box_autoadd_request_log_status(
    SseDeserializer deserializer,
  );

  @protected
  SessionConfig sse_decode_box_autoadd_session_config(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CreateMessageRequest sse_decode_create_message_request(
    SseDeserializer deserializer,
  );

  @protected
  CreateRequestLogRequest sse_decode_create_request_log_request(
    SseDeserializer deserializer,
  );

  @protected
  CreateSessionRequest sse_decode_create_session_request(
    SseDeserializer deserializer,
  );

  @protected
  DeleteMessagesResult sse_decode_delete_messages_result(
    SseDeserializer deserializer,
  );

  @protected
  DeleteResult sse_decode_delete_result(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<MessageRecord> sse_decode_list_message_record(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RequestLogSummary> sse_decode_list_request_log_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<SessionSummary> sse_decode_list_session_summary(
    SseDeserializer deserializer,
  );

  @protected
  LoadSessionResult sse_decode_load_session_result(
    SseDeserializer deserializer,
  );

  @protected
  MessageRecord sse_decode_message_record(SseDeserializer deserializer);

  @protected
  MessageRole sse_decode_message_role(SseDeserializer deserializer);

  @protected
  MessageStatus sse_decode_message_status(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  RequestLogStatus? sse_decode_opt_box_autoadd_request_log_status(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  RequestLog sse_decode_request_log(SseDeserializer deserializer);

  @protected
  RequestLogStatus sse_decode_request_log_status(SseDeserializer deserializer);

  @protected
  RequestLogSummary sse_decode_request_log_summary(
    SseDeserializer deserializer,
  );

  @protected
  SessionConfig sse_decode_session_config(SseDeserializer deserializer);

  @protected
  SessionMode sse_decode_session_mode(SseDeserializer deserializer);

  @protected
  SessionRuntimeState sse_decode_session_runtime_state(
    SseDeserializer deserializer,
  );

  @protected
  SessionSummary sse_decode_session_summary(SseDeserializer deserializer);

  @protected
  StreamingStatus sse_decode_streaming_status(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_create_message_request(
    CreateMessageRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_create_request_log_request(
    CreateRequestLogRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_create_session_request(
    CreateSessionRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_request_log_status(
    RequestLogStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_session_config(
    SessionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_create_message_request(
    CreateMessageRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_create_request_log_request(
    CreateRequestLogRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_create_session_request(
    CreateSessionRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delete_messages_result(
    DeleteMessagesResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delete_result(DeleteResult self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_message_record(
    List<MessageRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_request_log_summary(
    List<RequestLogSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_session_summary(
    List<SessionSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_load_session_result(
    LoadSessionResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_record(MessageRecord self, SseSerializer serializer);

  @protected
  void sse_encode_message_role(MessageRole self, SseSerializer serializer);

  @protected
  void sse_encode_message_status(MessageStatus self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_request_log_status(
    RequestLogStatus? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_request_log(RequestLog self, SseSerializer serializer);

  @protected
  void sse_encode_request_log_status(
    RequestLogStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_request_log_summary(
    RequestLogSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_config(SessionConfig self, SseSerializer serializer);

  @protected
  void sse_encode_session_mode(SessionMode self, SseSerializer serializer);

  @protected
  void sse_encode_session_runtime_state(
    SessionRuntimeState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_summary(
    SessionSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_streaming_status(
    StreamingStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustCoreWire implements BaseWire {
  factory RustCoreWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustCoreWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustCoreWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
