// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'frb_api.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustCore
    extends BaseEntrypoint<RustCoreApi, RustCoreApiImpl, RustCoreWire> {
  @internal
  static final instance = RustCore._();

  RustCore._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustCoreApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustCoreApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustCoreApiImpl, RustCoreWire> get apiImplConstructor =>
      RustCoreApiImpl.new;

  @override
  WireConstructor<RustCoreWire> get wireConstructor =>
      RustCoreWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 641736000;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rst_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustCoreApi extends BaseApi {
  Future<CleanupRequestLogsResult> crateFrbApiCleanupRequestLogs({
    required int olderThanDays,
    int? maxDelete,
  });

  Future<MessageRecord> crateFrbApiCreateMessage({
    required CreateMessageRequest message,
  });

  Future<RequestLog> crateFrbApiCreateRequestLog({
    required CreateRequestLogRequest seed,
  });

  Future<SessionConfig> crateFrbApiCreateSession({
    required CreateSessionRequest seed,
  });

  Future<DeleteMessagesResult> crateFrbApiDeleteMessages({
    required String sessionId,
    required List<String> messageIds,
  });

  Future<DeleteResult> crateFrbApiDeleteSession({required String sessionId});

  Future<RequestLog> crateFrbApiGetRequestLog({required String logId});

  Future<List<MessageRecord>> crateFrbApiListMessages({
    required String sessionId,
    int? limit,
  });

  Future<List<RequestLogSummary>> crateFrbApiListRequestLogs({
    String? sessionId,
    RequestLogStatus? status,
    int? limit,
  });

  Future<List<SessionSummary>> crateFrbApiListSessions();

  Future<LoadSessionResult> crateFrbApiLoadSession({required String sessionId});

  Future<SessionConfig> crateFrbApiRenameSession({
    required String sessionId,
    required String sessionName,
  });

  Future<SessionConfig> crateFrbApiSaveSession({required SessionConfig config});

  Future<MessageRecord> crateFrbApiSetMessageStatus({
    required String messageId,
    required MessageStatus status,
    String? errorMessage,
  });

  Future<MessageRecord> crateFrbApiSetMessageVisibility({
    required String messageId,
    required bool visible,
  });

  Future<String> crateFrbApiSetWorkspaceDir({required String path});

  Future<StreamingStatus> crateFrbApiStreamingStatusDefault();

  Future<MessageRecord> crateFrbApiUpdateMessageContent({
    required String messageId,
    required String content,
  });
}

class RustCoreApiImpl extends RustCoreApiImplPlatform implements RustCoreApi {
  RustCoreApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<CleanupRequestLogsResult> crateFrbApiCleanupRequestLogs({
    required int olderThanDays,
    int? maxDelete,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(olderThanDays, serializer);
          sse_encode_opt_box_autoadd_u_32(maxDelete, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_cleanup_request_logs_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFrbApiCleanupRequestLogsConstMeta,
        argValues: [olderThanDays, maxDelete],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiCleanupRequestLogsConstMeta =>
      const TaskConstMeta(
        debugName: "cleanup_request_logs",
        argNames: ["olderThanDays", "maxDelete"],
      );

  @override
  Future<MessageRecord> crateFrbApiCreateMessage({
    required CreateMessageRequest message,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_create_message_request(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_message_record,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFrbApiCreateMessageConstMeta,
        argValues: [message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiCreateMessageConstMeta =>
      const TaskConstMeta(debugName: "create_message", argNames: ["message"]);

  @override
  Future<RequestLog> crateFrbApiCreateRequestLog({
    required CreateRequestLogRequest seed,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_create_request_log_request(seed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_request_log,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFrbApiCreateRequestLogConstMeta,
        argValues: [seed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiCreateRequestLogConstMeta =>
      const TaskConstMeta(debugName: "create_request_log", argNames: ["seed"]);

  @override
  Future<SessionConfig> crateFrbApiCreateSession({
    required CreateSessionRequest seed,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_create_session_request(seed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_config,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFrbApiCreateSessionConstMeta,
        argValues: [seed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiCreateSessionConstMeta =>
      const TaskConstMeta(debugName: "create_session", argNames: ["seed"]);

  @override
  Future<DeleteMessagesResult> crateFrbApiDeleteMessages({
    required String sessionId,
    required List<String> messageIds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_list_String(messageIds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_delete_messages_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFrbApiDeleteMessagesConstMeta,
        argValues: [sessionId, messageIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiDeleteMessagesConstMeta => const TaskConstMeta(
    debugName: "delete_messages",
    argNames: ["sessionId", "messageIds"],
  );

  @override
  Future<DeleteResult> crateFrbApiDeleteSession({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_delete_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFrbApiDeleteSessionConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiDeleteSessionConstMeta =>
      const TaskConstMeta(debugName: "delete_session", argNames: ["sessionId"]);

  @override
  Future<RequestLog> crateFrbApiGetRequestLog({required String logId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(logId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_request_log,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFrbApiGetRequestLogConstMeta,
        argValues: [logId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiGetRequestLogConstMeta =>
      const TaskConstMeta(debugName: "get_request_log", argNames: ["logId"]);

  @override
  Future<List<MessageRecord>> crateFrbApiListMessages({
    required String sessionId,
    int? limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_opt_box_autoadd_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_message_record,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFrbApiListMessagesConstMeta,
        argValues: [sessionId, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiListMessagesConstMeta => const TaskConstMeta(
    debugName: "list_messages",
    argNames: ["sessionId", "limit"],
  );

  @override
  Future<List<RequestLogSummary>> crateFrbApiListRequestLogs({
    String? sessionId,
    RequestLogStatus? status,
    int? limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(sessionId, serializer);
          sse_encode_opt_box_autoadd_request_log_status(status, serializer);
          sse_encode_opt_box_autoadd_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_request_log_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFrbApiListRequestLogsConstMeta,
        argValues: [sessionId, status, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiListRequestLogsConstMeta => const TaskConstMeta(
    debugName: "list_request_logs",
    argNames: ["sessionId", "status", "limit"],
  );

  @override
  Future<List<SessionSummary>> crateFrbApiListSessions() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_session_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFrbApiListSessionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiListSessionsConstMeta =>
      const TaskConstMeta(debugName: "list_sessions", argNames: []);

  @override
  Future<LoadSessionResult> crateFrbApiLoadSession({
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_load_session_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFrbApiLoadSessionConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiLoadSessionConstMeta =>
      const TaskConstMeta(debugName: "load_session", argNames: ["sessionId"]);

  @override
  Future<SessionConfig> crateFrbApiRenameSession({
    required String sessionId,
    required String sessionName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(sessionName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_config,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFrbApiRenameSessionConstMeta,
        argValues: [sessionId, sessionName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiRenameSessionConstMeta => const TaskConstMeta(
    debugName: "rename_session",
    argNames: ["sessionId", "sessionName"],
  );

  @override
  Future<SessionConfig> crateFrbApiSaveSession({
    required SessionConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_session_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_config,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFrbApiSaveSessionConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiSaveSessionConstMeta =>
      const TaskConstMeta(debugName: "save_session", argNames: ["config"]);

  @override
  Future<MessageRecord> crateFrbApiSetMessageStatus({
    required String messageId,
    required MessageStatus status,
    String? errorMessage,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(messageId, serializer);
          sse_encode_message_status(status, serializer);
          sse_encode_opt_String(errorMessage, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_message_record,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFrbApiSetMessageStatusConstMeta,
        argValues: [messageId, status, errorMessage],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiSetMessageStatusConstMeta =>
      const TaskConstMeta(
        debugName: "set_message_status",
        argNames: ["messageId", "status", "errorMessage"],
      );

  @override
  Future<MessageRecord> crateFrbApiSetMessageVisibility({
    required String messageId,
    required bool visible,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(messageId, serializer);
          sse_encode_bool(visible, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_message_record,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFrbApiSetMessageVisibilityConstMeta,
        argValues: [messageId, visible],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiSetMessageVisibilityConstMeta =>
      const TaskConstMeta(
        debugName: "set_message_visibility",
        argNames: ["messageId", "visible"],
      );

  @override
  Future<String> crateFrbApiSetWorkspaceDir({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFrbApiSetWorkspaceDirConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiSetWorkspaceDirConstMeta =>
      const TaskConstMeta(debugName: "set_workspace_dir", argNames: ["path"]);

  @override
  Future<StreamingStatus> crateFrbApiStreamingStatusDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_streaming_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiStreamingStatusDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiStreamingStatusDefaultConstMeta =>
      const TaskConstMeta(debugName: "streaming_status_default", argNames: []);

  @override
  Future<MessageRecord> crateFrbApiUpdateMessageContent({
    required String messageId,
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(messageId, serializer);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_message_record,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFrbApiUpdateMessageContentConstMeta,
        argValues: [messageId, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiUpdateMessageContentConstMeta =>
      const TaskConstMeta(
        debugName: "update_message_content",
        argNames: ["messageId", "content"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CreateMessageRequest dco_decode_box_autoadd_create_message_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_create_message_request(raw);
  }

  @protected
  CreateRequestLogRequest dco_decode_box_autoadd_create_request_log_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_create_request_log_request(raw);
  }

  @protected
  CreateSessionRequest dco_decode_box_autoadd_create_session_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_create_session_request(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  RequestLogStatus dco_decode_box_autoadd_request_log_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_request_log_status(raw);
  }

  @protected
  SessionConfig dco_decode_box_autoadd_session_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_session_config(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CleanupRequestLogsResult dco_decode_cleanup_request_logs_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CleanupRequestLogsResult(
      scanned: dco_decode_u_32(arr[0]),
      deleted: dco_decode_u_32(arr[1]),
      hasMoreExpired: dco_decode_bool(arr[2]),
    );
  }

  @protected
  CreateMessageRequest dco_decode_create_message_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return CreateMessageRequest(
      sessionId: dco_decode_String(arr[0]),
      role: dco_decode_message_role(arr[1]),
      content: dco_decode_String(arr[2]),
      visible: dco_decode_bool(arr[3]),
      status: dco_decode_message_status(arr[4]),
    );
  }

  @protected
  CreateRequestLogRequest dco_decode_create_request_log_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return CreateRequestLogRequest(
      sessionId: dco_decode_String(arr[0]),
      provider: dco_decode_String(arr[1]),
      model: dco_decode_String(arr[2]),
      status: dco_decode_request_log_status(arr[3]),
      requestTime: dco_decode_String(arr[4]),
      responseTime: dco_decode_opt_String(arr[5]),
      durationMs: dco_decode_opt_box_autoadd_i_64(arr[6]),
      promptTokens: dco_decode_opt_box_autoadd_i_64(arr[7]),
      completionTokens: dco_decode_opt_box_autoadd_i_64(arr[8]),
      totalTokens: dco_decode_opt_box_autoadd_i_64(arr[9]),
      stopReason: dco_decode_opt_String(arr[10]),
      redacted: dco_decode_bool(arr[11]),
      payloadTruncated: dco_decode_bool(arr[12]),
      requestPreviewJson: dco_decode_opt_String(arr[13]),
      responsePreviewJson: dco_decode_opt_String(arr[14]),
    );
  }

  @protected
  CreateSessionRequest dco_decode_create_session_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return CreateSessionRequest(
      sessionName: dco_decode_String(arr[0]),
      mode: dco_decode_session_mode(arr[1]),
      mainApiConfigId: dco_decode_String(arr[2]),
      presetId: dco_decode_String(arr[3]),
      stWorldBookId: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  DeleteMessagesResult dco_decode_delete_messages_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return DeleteMessagesResult(
      deletedMessageIds: dco_decode_list_String(arr[0]),
    );
  }

  @protected
  DeleteResult dco_decode_delete_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return DeleteResult(deleted: dco_decode_bool(arr[0]));
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<MessageRecord> dco_decode_list_message_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_message_record).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RequestLogSummary> dco_decode_list_request_log_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_request_log_summary).toList();
  }

  @protected
  List<SessionSummary> dco_decode_list_session_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_session_summary).toList();
  }

  @protected
  LoadSessionResult dco_decode_load_session_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LoadSessionResult(
      config: dco_decode_session_config(arr[0]),
      runtime: dco_decode_session_runtime_state(arr[1]),
    );
  }

  @protected
  MessageRecord dco_decode_message_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return MessageRecord(
      messageId: dco_decode_String(arr[0]),
      sessionId: dco_decode_String(arr[1]),
      role: dco_decode_message_role(arr[2]),
      floorNo: dco_decode_opt_box_autoadd_i_64(arr[3]),
      content: dco_decode_String(arr[4]),
      visible: dco_decode_bool(arr[5]),
      status: dco_decode_message_status(arr[6]),
      errorMessage: dco_decode_opt_String(arr[7]),
      createdAt: dco_decode_String(arr[8]),
      updatedAt: dco_decode_String(arr[9]),
    );
  }

  @protected
  MessageRole dco_decode_message_role(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MessageRole.values[raw as int];
  }

  @protected
  MessageStatus dco_decode_message_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MessageStatus.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  RequestLogStatus? dco_decode_opt_box_autoadd_request_log_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_request_log_status(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  RequestLog dco_decode_request_log(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 16)
      throw Exception('unexpected arr length: expect 16 but see ${arr.length}');
    return RequestLog(
      logId: dco_decode_String(arr[0]),
      sessionId: dco_decode_String(arr[1]),
      provider: dco_decode_String(arr[2]),
      model: dco_decode_String(arr[3]),
      status: dco_decode_request_log_status(arr[4]),
      requestTime: dco_decode_String(arr[5]),
      responseTime: dco_decode_opt_String(arr[6]),
      durationMs: dco_decode_opt_box_autoadd_i_64(arr[7]),
      promptTokens: dco_decode_opt_box_autoadd_i_64(arr[8]),
      completionTokens: dco_decode_opt_box_autoadd_i_64(arr[9]),
      totalTokens: dco_decode_opt_box_autoadd_i_64(arr[10]),
      stopReason: dco_decode_opt_String(arr[11]),
      redacted: dco_decode_bool(arr[12]),
      payloadTruncated: dco_decode_bool(arr[13]),
      requestPreviewJson: dco_decode_opt_String(arr[14]),
      responsePreviewJson: dco_decode_opt_String(arr[15]),
    );
  }

  @protected
  RequestLogStatus dco_decode_request_log_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RequestLogStatus.values[raw as int];
  }

  @protected
  RequestLogSummary dco_decode_request_log_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return RequestLogSummary(
      logId: dco_decode_String(arr[0]),
      sessionId: dco_decode_String(arr[1]),
      provider: dco_decode_String(arr[2]),
      model: dco_decode_String(arr[3]),
      status: dco_decode_request_log_status(arr[4]),
      requestTime: dco_decode_String(arr[5]),
      durationMs: dco_decode_opt_box_autoadd_i_64(arr[6]),
      redacted: dco_decode_bool(arr[7]),
      payloadTruncated: dco_decode_bool(arr[8]),
    );
  }

  @protected
  SessionConfig dco_decode_session_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return SessionConfig(
      sessionId: dco_decode_String(arr[0]),
      sessionName: dco_decode_String(arr[1]),
      mode: dco_decode_session_mode(arr[2]),
      mainApiConfigId: dco_decode_String(arr[3]),
      presetId: dco_decode_String(arr[4]),
      stWorldBookId: dco_decode_opt_String(arr[5]),
      createdAt: dco_decode_String(arr[6]),
      updatedAt: dco_decode_String(arr[7]),
    );
  }

  @protected
  SessionMode dco_decode_session_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SessionMode.values[raw as int];
  }

  @protected
  SessionRuntimeState dco_decode_session_runtime_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return SessionRuntimeState(
      sessionId: dco_decode_String(arr[0]),
      activeMessageId: dco_decode_opt_String(arr[1]),
      streamingStatus: dco_decode_streaming_status(arr[2]),
      lastError: dco_decode_opt_String(arr[3]),
      lastPromptTokenEstimate: dco_decode_opt_box_autoadd_i_64(arr[4]),
      lastCompletionTokenEstimate: dco_decode_opt_box_autoadd_i_64(arr[5]),
      lastUsedModel: dco_decode_opt_String(arr[6]),
      lastRequestStartedAt: dco_decode_opt_String(arr[7]),
      lastRequestFinishedAt: dco_decode_opt_String(arr[8]),
      updatedAt: dco_decode_String(arr[9]),
    );
  }

  @protected
  SessionSummary dco_decode_session_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SessionSummary(
      sessionId: dco_decode_String(arr[0]),
      sessionName: dco_decode_String(arr[1]),
      mode: dco_decode_session_mode(arr[2]),
      updatedAt: dco_decode_String(arr[3]),
    );
  }

  @protected
  StreamingStatus dco_decode_streaming_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return StreamingStatus.values[raw as int];
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CreateMessageRequest sse_decode_box_autoadd_create_message_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_create_message_request(deserializer));
  }

  @protected
  CreateRequestLogRequest sse_decode_box_autoadd_create_request_log_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_create_request_log_request(deserializer));
  }

  @protected
  CreateSessionRequest sse_decode_box_autoadd_create_session_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_create_session_request(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  RequestLogStatus sse_decode_box_autoadd_request_log_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_request_log_status(deserializer));
  }

  @protected
  SessionConfig sse_decode_box_autoadd_session_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_session_config(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  CleanupRequestLogsResult sse_decode_cleanup_request_logs_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_scanned = sse_decode_u_32(deserializer);
    var var_deleted = sse_decode_u_32(deserializer);
    var var_hasMoreExpired = sse_decode_bool(deserializer);
    return CleanupRequestLogsResult(
      scanned: var_scanned,
      deleted: var_deleted,
      hasMoreExpired: var_hasMoreExpired,
    );
  }

  @protected
  CreateMessageRequest sse_decode_create_message_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_role = sse_decode_message_role(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_visible = sse_decode_bool(deserializer);
    var var_status = sse_decode_message_status(deserializer);
    return CreateMessageRequest(
      sessionId: var_sessionId,
      role: var_role,
      content: var_content,
      visible: var_visible,
      status: var_status,
    );
  }

  @protected
  CreateRequestLogRequest sse_decode_create_request_log_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_provider = sse_decode_String(deserializer);
    var var_model = sse_decode_String(deserializer);
    var var_status = sse_decode_request_log_status(deserializer);
    var var_requestTime = sse_decode_String(deserializer);
    var var_responseTime = sse_decode_opt_String(deserializer);
    var var_durationMs = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_promptTokens = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_completionTokens = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_totalTokens = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_stopReason = sse_decode_opt_String(deserializer);
    var var_redacted = sse_decode_bool(deserializer);
    var var_payloadTruncated = sse_decode_bool(deserializer);
    var var_requestPreviewJson = sse_decode_opt_String(deserializer);
    var var_responsePreviewJson = sse_decode_opt_String(deserializer);
    return CreateRequestLogRequest(
      sessionId: var_sessionId,
      provider: var_provider,
      model: var_model,
      status: var_status,
      requestTime: var_requestTime,
      responseTime: var_responseTime,
      durationMs: var_durationMs,
      promptTokens: var_promptTokens,
      completionTokens: var_completionTokens,
      totalTokens: var_totalTokens,
      stopReason: var_stopReason,
      redacted: var_redacted,
      payloadTruncated: var_payloadTruncated,
      requestPreviewJson: var_requestPreviewJson,
      responsePreviewJson: var_responsePreviewJson,
    );
  }

  @protected
  CreateSessionRequest sse_decode_create_session_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionName = sse_decode_String(deserializer);
    var var_mode = sse_decode_session_mode(deserializer);
    var var_mainApiConfigId = sse_decode_String(deserializer);
    var var_presetId = sse_decode_String(deserializer);
    var var_stWorldBookId = sse_decode_opt_String(deserializer);
    return CreateSessionRequest(
      sessionName: var_sessionName,
      mode: var_mode,
      mainApiConfigId: var_mainApiConfigId,
      presetId: var_presetId,
      stWorldBookId: var_stWorldBookId,
    );
  }

  @protected
  DeleteMessagesResult sse_decode_delete_messages_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deletedMessageIds = sse_decode_list_String(deserializer);
    return DeleteMessagesResult(deletedMessageIds: var_deletedMessageIds);
  }

  @protected
  DeleteResult sse_decode_delete_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deleted = sse_decode_bool(deserializer);
    return DeleteResult(deleted: var_deleted);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<MessageRecord> sse_decode_list_message_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MessageRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_message_record(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RequestLogSummary> sse_decode_list_request_log_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RequestLogSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_request_log_summary(deserializer));
    }
    return ans_;
  }

  @protected
  List<SessionSummary> sse_decode_list_session_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SessionSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_session_summary(deserializer));
    }
    return ans_;
  }

  @protected
  LoadSessionResult sse_decode_load_session_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_config = sse_decode_session_config(deserializer);
    var var_runtime = sse_decode_session_runtime_state(deserializer);
    return LoadSessionResult(config: var_config, runtime: var_runtime);
  }

  @protected
  MessageRecord sse_decode_message_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_messageId = sse_decode_String(deserializer);
    var var_sessionId = sse_decode_String(deserializer);
    var var_role = sse_decode_message_role(deserializer);
    var var_floorNo = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_visible = sse_decode_bool(deserializer);
    var var_status = sse_decode_message_status(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    return MessageRecord(
      messageId: var_messageId,
      sessionId: var_sessionId,
      role: var_role,
      floorNo: var_floorNo,
      content: var_content,
      visible: var_visible,
      status: var_status,
      errorMessage: var_errorMessage,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  MessageRole sse_decode_message_role(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MessageRole.values[inner];
  }

  @protected
  MessageStatus sse_decode_message_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MessageStatus.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RequestLogStatus? sse_decode_opt_box_autoadd_request_log_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_request_log_status(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RequestLog sse_decode_request_log(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_logId = sse_decode_String(deserializer);
    var var_sessionId = sse_decode_String(deserializer);
    var var_provider = sse_decode_String(deserializer);
    var var_model = sse_decode_String(deserializer);
    var var_status = sse_decode_request_log_status(deserializer);
    var var_requestTime = sse_decode_String(deserializer);
    var var_responseTime = sse_decode_opt_String(deserializer);
    var var_durationMs = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_promptTokens = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_completionTokens = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_totalTokens = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_stopReason = sse_decode_opt_String(deserializer);
    var var_redacted = sse_decode_bool(deserializer);
    var var_payloadTruncated = sse_decode_bool(deserializer);
    var var_requestPreviewJson = sse_decode_opt_String(deserializer);
    var var_responsePreviewJson = sse_decode_opt_String(deserializer);
    return RequestLog(
      logId: var_logId,
      sessionId: var_sessionId,
      provider: var_provider,
      model: var_model,
      status: var_status,
      requestTime: var_requestTime,
      responseTime: var_responseTime,
      durationMs: var_durationMs,
      promptTokens: var_promptTokens,
      completionTokens: var_completionTokens,
      totalTokens: var_totalTokens,
      stopReason: var_stopReason,
      redacted: var_redacted,
      payloadTruncated: var_payloadTruncated,
      requestPreviewJson: var_requestPreviewJson,
      responsePreviewJson: var_responsePreviewJson,
    );
  }

  @protected
  RequestLogStatus sse_decode_request_log_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RequestLogStatus.values[inner];
  }

  @protected
  RequestLogSummary sse_decode_request_log_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_logId = sse_decode_String(deserializer);
    var var_sessionId = sse_decode_String(deserializer);
    var var_provider = sse_decode_String(deserializer);
    var var_model = sse_decode_String(deserializer);
    var var_status = sse_decode_request_log_status(deserializer);
    var var_requestTime = sse_decode_String(deserializer);
    var var_durationMs = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_redacted = sse_decode_bool(deserializer);
    var var_payloadTruncated = sse_decode_bool(deserializer);
    return RequestLogSummary(
      logId: var_logId,
      sessionId: var_sessionId,
      provider: var_provider,
      model: var_model,
      status: var_status,
      requestTime: var_requestTime,
      durationMs: var_durationMs,
      redacted: var_redacted,
      payloadTruncated: var_payloadTruncated,
    );
  }

  @protected
  SessionConfig sse_decode_session_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_sessionName = sse_decode_String(deserializer);
    var var_mode = sse_decode_session_mode(deserializer);
    var var_mainApiConfigId = sse_decode_String(deserializer);
    var var_presetId = sse_decode_String(deserializer);
    var var_stWorldBookId = sse_decode_opt_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    return SessionConfig(
      sessionId: var_sessionId,
      sessionName: var_sessionName,
      mode: var_mode,
      mainApiConfigId: var_mainApiConfigId,
      presetId: var_presetId,
      stWorldBookId: var_stWorldBookId,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  SessionMode sse_decode_session_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SessionMode.values[inner];
  }

  @protected
  SessionRuntimeState sse_decode_session_runtime_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_activeMessageId = sse_decode_opt_String(deserializer);
    var var_streamingStatus = sse_decode_streaming_status(deserializer);
    var var_lastError = sse_decode_opt_String(deserializer);
    var var_lastPromptTokenEstimate = sse_decode_opt_box_autoadd_i_64(
      deserializer,
    );
    var var_lastCompletionTokenEstimate = sse_decode_opt_box_autoadd_i_64(
      deserializer,
    );
    var var_lastUsedModel = sse_decode_opt_String(deserializer);
    var var_lastRequestStartedAt = sse_decode_opt_String(deserializer);
    var var_lastRequestFinishedAt = sse_decode_opt_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    return SessionRuntimeState(
      sessionId: var_sessionId,
      activeMessageId: var_activeMessageId,
      streamingStatus: var_streamingStatus,
      lastError: var_lastError,
      lastPromptTokenEstimate: var_lastPromptTokenEstimate,
      lastCompletionTokenEstimate: var_lastCompletionTokenEstimate,
      lastUsedModel: var_lastUsedModel,
      lastRequestStartedAt: var_lastRequestStartedAt,
      lastRequestFinishedAt: var_lastRequestFinishedAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  SessionSummary sse_decode_session_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_sessionName = sse_decode_String(deserializer);
    var var_mode = sse_decode_session_mode(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    return SessionSummary(
      sessionId: var_sessionId,
      sessionName: var_sessionName,
      mode: var_mode,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  StreamingStatus sse_decode_streaming_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return StreamingStatus.values[inner];
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_create_message_request(
    CreateMessageRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_create_message_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_create_request_log_request(
    CreateRequestLogRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_create_request_log_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_create_session_request(
    CreateSessionRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_create_session_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_request_log_status(
    RequestLogStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_request_log_status(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_session_config(
    SessionConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_session_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_cleanup_request_logs_result(
    CleanupRequestLogsResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.scanned, serializer);
    sse_encode_u_32(self.deleted, serializer);
    sse_encode_bool(self.hasMoreExpired, serializer);
  }

  @protected
  void sse_encode_create_message_request(
    CreateMessageRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_message_role(self.role, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_bool(self.visible, serializer);
    sse_encode_message_status(self.status, serializer);
  }

  @protected
  void sse_encode_create_request_log_request(
    CreateRequestLogRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_String(self.provider, serializer);
    sse_encode_String(self.model, serializer);
    sse_encode_request_log_status(self.status, serializer);
    sse_encode_String(self.requestTime, serializer);
    sse_encode_opt_String(self.responseTime, serializer);
    sse_encode_opt_box_autoadd_i_64(self.durationMs, serializer);
    sse_encode_opt_box_autoadd_i_64(self.promptTokens, serializer);
    sse_encode_opt_box_autoadd_i_64(self.completionTokens, serializer);
    sse_encode_opt_box_autoadd_i_64(self.totalTokens, serializer);
    sse_encode_opt_String(self.stopReason, serializer);
    sse_encode_bool(self.redacted, serializer);
    sse_encode_bool(self.payloadTruncated, serializer);
    sse_encode_opt_String(self.requestPreviewJson, serializer);
    sse_encode_opt_String(self.responsePreviewJson, serializer);
  }

  @protected
  void sse_encode_create_session_request(
    CreateSessionRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionName, serializer);
    sse_encode_session_mode(self.mode, serializer);
    sse_encode_String(self.mainApiConfigId, serializer);
    sse_encode_String(self.presetId, serializer);
    sse_encode_opt_String(self.stWorldBookId, serializer);
  }

  @protected
  void sse_encode_delete_messages_result(
    DeleteMessagesResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.deletedMessageIds, serializer);
  }

  @protected
  void sse_encode_delete_result(DeleteResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.deleted, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_message_record(
    List<MessageRecord> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_message_record(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_request_log_summary(
    List<RequestLogSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_request_log_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_session_summary(
    List<SessionSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_session_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_load_session_result(
    LoadSessionResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_session_config(self.config, serializer);
    sse_encode_session_runtime_state(self.runtime, serializer);
  }

  @protected
  void sse_encode_message_record(MessageRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.messageId, serializer);
    sse_encode_String(self.sessionId, serializer);
    sse_encode_message_role(self.role, serializer);
    sse_encode_opt_box_autoadd_i_64(self.floorNo, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_bool(self.visible, serializer);
    sse_encode_message_status(self.status, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_message_role(MessageRole self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_message_status(MessageStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_request_log_status(
    RequestLogStatus? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_request_log_status(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_request_log(RequestLog self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.logId, serializer);
    sse_encode_String(self.sessionId, serializer);
    sse_encode_String(self.provider, serializer);
    sse_encode_String(self.model, serializer);
    sse_encode_request_log_status(self.status, serializer);
    sse_encode_String(self.requestTime, serializer);
    sse_encode_opt_String(self.responseTime, serializer);
    sse_encode_opt_box_autoadd_i_64(self.durationMs, serializer);
    sse_encode_opt_box_autoadd_i_64(self.promptTokens, serializer);
    sse_encode_opt_box_autoadd_i_64(self.completionTokens, serializer);
    sse_encode_opt_box_autoadd_i_64(self.totalTokens, serializer);
    sse_encode_opt_String(self.stopReason, serializer);
    sse_encode_bool(self.redacted, serializer);
    sse_encode_bool(self.payloadTruncated, serializer);
    sse_encode_opt_String(self.requestPreviewJson, serializer);
    sse_encode_opt_String(self.responsePreviewJson, serializer);
  }

  @protected
  void sse_encode_request_log_status(
    RequestLogStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_request_log_summary(
    RequestLogSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.logId, serializer);
    sse_encode_String(self.sessionId, serializer);
    sse_encode_String(self.provider, serializer);
    sse_encode_String(self.model, serializer);
    sse_encode_request_log_status(self.status, serializer);
    sse_encode_String(self.requestTime, serializer);
    sse_encode_opt_box_autoadd_i_64(self.durationMs, serializer);
    sse_encode_bool(self.redacted, serializer);
    sse_encode_bool(self.payloadTruncated, serializer);
  }

  @protected
  void sse_encode_session_config(SessionConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_String(self.sessionName, serializer);
    sse_encode_session_mode(self.mode, serializer);
    sse_encode_String(self.mainApiConfigId, serializer);
    sse_encode_String(self.presetId, serializer);
    sse_encode_opt_String(self.stWorldBookId, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_session_mode(SessionMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_session_runtime_state(
    SessionRuntimeState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_opt_String(self.activeMessageId, serializer);
    sse_encode_streaming_status(self.streamingStatus, serializer);
    sse_encode_opt_String(self.lastError, serializer);
    sse_encode_opt_box_autoadd_i_64(self.lastPromptTokenEstimate, serializer);
    sse_encode_opt_box_autoadd_i_64(
      self.lastCompletionTokenEstimate,
      serializer,
    );
    sse_encode_opt_String(self.lastUsedModel, serializer);
    sse_encode_opt_String(self.lastRequestStartedAt, serializer);
    sse_encode_opt_String(self.lastRequestFinishedAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_session_summary(
    SessionSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_String(self.sessionName, serializer);
    sse_encode_session_mode(self.mode, serializer);
    sse_encode_String(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_streaming_status(
    StreamingStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
