// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_status_side_effects`, `copy_dir_recursive`, `legacy_workspace_root`, `migrate_workspace_if_needed`, `mutate_message`, `normalize_optional`, `now_rfc3339`, `read_request_log_file`, `read_session_file`, `reconcile_inflight_state`, `request_log_file_path`, `request_log_paths`, `request_logs_dir`, `session_file_path`, `session_paths`, `sessions_dir`, `touch_session`, `validate_mode_binding`, `validate_session_name`, `workspace_root`, `write_request_log_file`, `write_session_file`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SessionFile`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<List<SessionSummary>> listSessions() =>
    RustCore.instance.api.crateFrbApiListSessions();

Future<SessionConfig> createSession({required CreateSessionRequest seed}) =>
    RustCore.instance.api.crateFrbApiCreateSession(seed: seed);

Future<SessionConfig> saveSession({required SessionConfig config}) =>
    RustCore.instance.api.crateFrbApiSaveSession(config: config);

Future<SessionConfig> renameSession({
  required String sessionId,
  required String sessionName,
}) => RustCore.instance.api.crateFrbApiRenameSession(
  sessionId: sessionId,
  sessionName: sessionName,
);

Future<DeleteResult> deleteSession({required String sessionId}) =>
    RustCore.instance.api.crateFrbApiDeleteSession(sessionId: sessionId);

Future<LoadSessionResult> loadSession({required String sessionId}) =>
    RustCore.instance.api.crateFrbApiLoadSession(sessionId: sessionId);

Future<MessageRecord> createMessage({required CreateMessageRequest message}) =>
    RustCore.instance.api.crateFrbApiCreateMessage(message: message);

Future<MessageRecord> updateMessageContent({
  required String messageId,
  required String content,
}) => RustCore.instance.api.crateFrbApiUpdateMessageContent(
  messageId: messageId,
  content: content,
);

Future<MessageRecord> setMessageStatus({
  required String messageId,
  required MessageStatus status,
  String? errorMessage,
}) => RustCore.instance.api.crateFrbApiSetMessageStatus(
  messageId: messageId,
  status: status,
  errorMessage: errorMessage,
);

Future<MessageRecord> setMessageVisibility({
  required String messageId,
  required bool visible,
}) => RustCore.instance.api.crateFrbApiSetMessageVisibility(
  messageId: messageId,
  visible: visible,
);

Future<DeleteMessagesResult> deleteMessages({
  required String sessionId,
  required List<String> messageIds,
}) => RustCore.instance.api.crateFrbApiDeleteMessages(
  sessionId: sessionId,
  messageIds: messageIds,
);

Future<List<MessageRecord>> listMessages({
  required String sessionId,
  int? limit,
}) => RustCore.instance.api.crateFrbApiListMessages(
  sessionId: sessionId,
  limit: limit,
);

Future<RequestLog> createRequestLog({required CreateRequestLogRequest seed}) =>
    RustCore.instance.api.crateFrbApiCreateRequestLog(seed: seed);

Future<List<RequestLogSummary>> listRequestLogs({
  String? sessionId,
  RequestLogStatus? status,
  int? limit,
}) => RustCore.instance.api.crateFrbApiListRequestLogs(
  sessionId: sessionId,
  status: status,
  limit: limit,
);

Future<RequestLog> getRequestLog({required String logId}) =>
    RustCore.instance.api.crateFrbApiGetRequestLog(logId: logId);

Future<String> setWorkspaceDir({required String path}) =>
    RustCore.instance.api.crateFrbApiSetWorkspaceDir(path: path);

class CreateMessageRequest {
  final String sessionId;
  final MessageRole role;
  final String content;
  final bool visible;
  final MessageStatus status;

  const CreateMessageRequest({
    required this.sessionId,
    required this.role,
    required this.content,
    required this.visible,
    required this.status,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      role.hashCode ^
      content.hashCode ^
      visible.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateMessageRequest &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          role == other.role &&
          content == other.content &&
          visible == other.visible &&
          status == other.status;
}

class CreateRequestLogRequest {
  final String sessionId;
  final String provider;
  final String model;
  final RequestLogStatus status;
  final String requestTime;
  final String? responseTime;
  final PlatformInt64? durationMs;
  final PlatformInt64? promptTokens;
  final PlatformInt64? completionTokens;
  final PlatformInt64? totalTokens;
  final String? stopReason;
  final bool redacted;
  final bool payloadTruncated;
  final String? requestPreviewJson;
  final String? responsePreviewJson;

  const CreateRequestLogRequest({
    required this.sessionId,
    required this.provider,
    required this.model,
    required this.status,
    required this.requestTime,
    this.responseTime,
    this.durationMs,
    this.promptTokens,
    this.completionTokens,
    this.totalTokens,
    this.stopReason,
    required this.redacted,
    required this.payloadTruncated,
    this.requestPreviewJson,
    this.responsePreviewJson,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      provider.hashCode ^
      model.hashCode ^
      status.hashCode ^
      requestTime.hashCode ^
      responseTime.hashCode ^
      durationMs.hashCode ^
      promptTokens.hashCode ^
      completionTokens.hashCode ^
      totalTokens.hashCode ^
      stopReason.hashCode ^
      redacted.hashCode ^
      payloadTruncated.hashCode ^
      requestPreviewJson.hashCode ^
      responsePreviewJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateRequestLogRequest &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          provider == other.provider &&
          model == other.model &&
          status == other.status &&
          requestTime == other.requestTime &&
          responseTime == other.responseTime &&
          durationMs == other.durationMs &&
          promptTokens == other.promptTokens &&
          completionTokens == other.completionTokens &&
          totalTokens == other.totalTokens &&
          stopReason == other.stopReason &&
          redacted == other.redacted &&
          payloadTruncated == other.payloadTruncated &&
          requestPreviewJson == other.requestPreviewJson &&
          responsePreviewJson == other.responsePreviewJson;
}

class CreateSessionRequest {
  final String sessionName;
  final SessionMode mode;
  final String mainApiConfigId;
  final String presetId;
  final String? stWorldBookId;

  const CreateSessionRequest({
    required this.sessionName,
    required this.mode,
    required this.mainApiConfigId,
    required this.presetId,
    this.stWorldBookId,
  });

  @override
  int get hashCode =>
      sessionName.hashCode ^
      mode.hashCode ^
      mainApiConfigId.hashCode ^
      presetId.hashCode ^
      stWorldBookId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateSessionRequest &&
          runtimeType == other.runtimeType &&
          sessionName == other.sessionName &&
          mode == other.mode &&
          mainApiConfigId == other.mainApiConfigId &&
          presetId == other.presetId &&
          stWorldBookId == other.stWorldBookId;
}

class DeleteMessagesResult {
  final List<String> deletedMessageIds;

  const DeleteMessagesResult({required this.deletedMessageIds});

  @override
  int get hashCode => deletedMessageIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteMessagesResult &&
          runtimeType == other.runtimeType &&
          deletedMessageIds == other.deletedMessageIds;
}

class DeleteResult {
  final bool deleted;

  const DeleteResult({required this.deleted});

  @override
  int get hashCode => deleted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteResult &&
          runtimeType == other.runtimeType &&
          deleted == other.deleted;
}

class LoadSessionResult {
  final SessionConfig config;
  final SessionRuntimeState runtime;

  const LoadSessionResult({required this.config, required this.runtime});

  @override
  int get hashCode => config.hashCode ^ runtime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoadSessionResult &&
          runtimeType == other.runtimeType &&
          config == other.config &&
          runtime == other.runtime;
}

class MessageRecord {
  final String messageId;
  final String sessionId;
  final MessageRole role;
  final String content;
  final bool visible;
  final MessageStatus status;
  final String? errorMessage;
  final String createdAt;
  final String updatedAt;

  const MessageRecord({
    required this.messageId,
    required this.sessionId,
    required this.role,
    required this.content,
    required this.visible,
    required this.status,
    this.errorMessage,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      sessionId.hashCode ^
      role.hashCode ^
      content.hashCode ^
      visible.hashCode ^
      status.hashCode ^
      errorMessage.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageRecord &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          sessionId == other.sessionId &&
          role == other.role &&
          content == other.content &&
          visible == other.visible &&
          status == other.status &&
          errorMessage == other.errorMessage &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

enum MessageRole { system, user, assistant }

enum MessageStatus { pending, streaming, completed, error }

class RequestLog {
  final String logId;
  final String sessionId;
  final String provider;
  final String model;
  final RequestLogStatus status;
  final String requestTime;
  final String? responseTime;
  final PlatformInt64? durationMs;
  final PlatformInt64? promptTokens;
  final PlatformInt64? completionTokens;
  final PlatformInt64? totalTokens;
  final String? stopReason;
  final bool redacted;
  final bool payloadTruncated;
  final String? requestPreviewJson;
  final String? responsePreviewJson;

  const RequestLog({
    required this.logId,
    required this.sessionId,
    required this.provider,
    required this.model,
    required this.status,
    required this.requestTime,
    this.responseTime,
    this.durationMs,
    this.promptTokens,
    this.completionTokens,
    this.totalTokens,
    this.stopReason,
    required this.redacted,
    required this.payloadTruncated,
    this.requestPreviewJson,
    this.responsePreviewJson,
  });

  @override
  int get hashCode =>
      logId.hashCode ^
      sessionId.hashCode ^
      provider.hashCode ^
      model.hashCode ^
      status.hashCode ^
      requestTime.hashCode ^
      responseTime.hashCode ^
      durationMs.hashCode ^
      promptTokens.hashCode ^
      completionTokens.hashCode ^
      totalTokens.hashCode ^
      stopReason.hashCode ^
      redacted.hashCode ^
      payloadTruncated.hashCode ^
      requestPreviewJson.hashCode ^
      responsePreviewJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RequestLog &&
          runtimeType == other.runtimeType &&
          logId == other.logId &&
          sessionId == other.sessionId &&
          provider == other.provider &&
          model == other.model &&
          status == other.status &&
          requestTime == other.requestTime &&
          responseTime == other.responseTime &&
          durationMs == other.durationMs &&
          promptTokens == other.promptTokens &&
          completionTokens == other.completionTokens &&
          totalTokens == other.totalTokens &&
          stopReason == other.stopReason &&
          redacted == other.redacted &&
          payloadTruncated == other.payloadTruncated &&
          requestPreviewJson == other.requestPreviewJson &&
          responsePreviewJson == other.responsePreviewJson;
}

enum RequestLogStatus { success, error }

class RequestLogSummary {
  final String logId;
  final String sessionId;
  final String provider;
  final String model;
  final RequestLogStatus status;
  final String requestTime;
  final PlatformInt64? durationMs;
  final bool redacted;
  final bool payloadTruncated;

  const RequestLogSummary({
    required this.logId,
    required this.sessionId,
    required this.provider,
    required this.model,
    required this.status,
    required this.requestTime,
    this.durationMs,
    required this.redacted,
    required this.payloadTruncated,
  });

  @override
  int get hashCode =>
      logId.hashCode ^
      sessionId.hashCode ^
      provider.hashCode ^
      model.hashCode ^
      status.hashCode ^
      requestTime.hashCode ^
      durationMs.hashCode ^
      redacted.hashCode ^
      payloadTruncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RequestLogSummary &&
          runtimeType == other.runtimeType &&
          logId == other.logId &&
          sessionId == other.sessionId &&
          provider == other.provider &&
          model == other.model &&
          status == other.status &&
          requestTime == other.requestTime &&
          durationMs == other.durationMs &&
          redacted == other.redacted &&
          payloadTruncated == other.payloadTruncated;
}

class SessionConfig {
  final String sessionId;
  final String sessionName;
  final SessionMode mode;
  final String mainApiConfigId;
  final String presetId;
  final String? stWorldBookId;
  final String createdAt;
  final String updatedAt;

  const SessionConfig({
    required this.sessionId,
    required this.sessionName,
    required this.mode,
    required this.mainApiConfigId,
    required this.presetId,
    this.stWorldBookId,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      sessionName.hashCode ^
      mode.hashCode ^
      mainApiConfigId.hashCode ^
      presetId.hashCode ^
      stWorldBookId.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionConfig &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          sessionName == other.sessionName &&
          mode == other.mode &&
          mainApiConfigId == other.mainApiConfigId &&
          presetId == other.presetId &&
          stWorldBookId == other.stWorldBookId &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

enum SessionMode { st, rst }

class SessionRuntimeState {
  final String sessionId;
  final String? activeMessageId;
  final StreamingStatus streamingStatus;
  final String? lastError;
  final PlatformInt64? lastPromptTokenEstimate;
  final PlatformInt64? lastCompletionTokenEstimate;
  final String? lastUsedModel;
  final String? lastRequestStartedAt;
  final String? lastRequestFinishedAt;
  final String updatedAt;

  const SessionRuntimeState({
    required this.sessionId,
    this.activeMessageId,
    required this.streamingStatus,
    this.lastError,
    this.lastPromptTokenEstimate,
    this.lastCompletionTokenEstimate,
    this.lastUsedModel,
    this.lastRequestStartedAt,
    this.lastRequestFinishedAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      activeMessageId.hashCode ^
      streamingStatus.hashCode ^
      lastError.hashCode ^
      lastPromptTokenEstimate.hashCode ^
      lastCompletionTokenEstimate.hashCode ^
      lastUsedModel.hashCode ^
      lastRequestStartedAt.hashCode ^
      lastRequestFinishedAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionRuntimeState &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          activeMessageId == other.activeMessageId &&
          streamingStatus == other.streamingStatus &&
          lastError == other.lastError &&
          lastPromptTokenEstimate == other.lastPromptTokenEstimate &&
          lastCompletionTokenEstimate == other.lastCompletionTokenEstimate &&
          lastUsedModel == other.lastUsedModel &&
          lastRequestStartedAt == other.lastRequestStartedAt &&
          lastRequestFinishedAt == other.lastRequestFinishedAt &&
          updatedAt == other.updatedAt;
}

class SessionSummary {
  final String sessionId;
  final String sessionName;
  final SessionMode mode;
  final String updatedAt;

  const SessionSummary({
    required this.sessionId,
    required this.sessionName,
    required this.mode,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      sessionName.hashCode ^
      mode.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionSummary &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          sessionName == other.sessionName &&
          mode == other.mode &&
          updatedAt == other.updatedAt;
}

enum StreamingStatus {
  idle,
  receiving,
  error;

  static Future<StreamingStatus> default_() =>
      RustCore.instance.api.crateFrbApiStreamingStatusDefault();
}
